export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const SET_SPINNER_MESSAGE = 'SET_SPINNER_MESSAGE';
export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST';

export const SET_ORDER_DATA = 'SET_ORDER_DATA';
export const REMOVE_ALL_ORDER_DETAIL = 'REMOVE_ALL_ORDER_DETAIL';
export const REMOVE_SELECTED_ORDER = 'REMOVE_SELECTED_ORDER';

export const SET_TOKEN='SET_TOKEN';
export const SET_STATUS='SET_STATUS';
export const SET_USERNAME='SET_USERNAME';
