export const NAVIGATION_STACK = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  MAIN_HOME:'MAIN_HOME',
  HOME: 'HOME',
  MAIN_AUTH: 'MAIN_AUTH',
  CHAT: 'CHAT',
  NOTIFICATION: 'NOTIFICATION',
  SIGN_UP: 'SIGN_UP',
  PROFILE: 'PROFILE',
};
