import StartingPage from "../screens/Starting/Start1";

export const NAVIGATION_STACK = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  MAIN_HOME:'MAIN_HOME',
  HOME: 'HOME',
  MAIN_AUTH: 'MAIN_AUTH',
  CHAT: 'CHAT',
  NOTIFICATION: 'NOTIFICATION',
  SIGN_UP: 'SIGN_UP',
  PROFILE: 'PROFILE',
  START1 : 'START1' ,
  START2: 'START2',
  START3: 'START3',
  START4: 'START4',
  GETTINGSTARTNEW: 'GETTINGSTARTNEW',
 
};
