import {customerType} from '../type';

export declare type StackParameterList = {
  SPLASH: undefined;
  LOGIN: undefined;
  NEW_SPARE_PARTS: undefined;
  SPARE_PARTS_TYPES: undefined;
  SPARE_PARTS: undefined;
  NEW_PRODUCTS: undefined;
  HELP_CENTER: undefined;
  STARTING: undefined;
  FAVORITES: undefined;
  PAYMENT: undefined;
  PAYMENT_METHOD: undefined;
  ADD_NEW_CARD: undefined;
  MAIN_HOME: undefined;
  MACHINERY: undefined;
  MACHINERY_LIST: undefined;
  MACHINE_DETAILS: undefined;
  SPARE_PARTS_DETAILS: undefined;
  EDIT_PROFILE: undefined;
  CATEGORIES: undefined;
  SERVICE_REQUESTS: undefined;
  HOME: undefined;
  CHAT: undefined;
  SETTINGS: undefined;
  NOTIFICATION: undefined;
  CHECKOUT: undefined;
  SIGN_UP: undefined;
  MAIN_AUTH: undefined;
  PROFILE: undefined;
  START1: undefined;
  START2: undefined;
  START3: undefined;
  START4: undefined;
};
